# Generated by Django 4.2 on 2023-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_product_carbohydrates_remove_product_energy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
