# Generated by Django 4.2 on 2023-09-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_product_carbohydrates_product_energy_product_fat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="carbohydrates",
        ),
        migrations.RemoveField(
            model_name="product",
            name="energy",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="product",
            name="proteins",
        ),
        migrations.RemoveField(
            model_name="product",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="product",
            name="saturated_fat",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sugars",
        ),
    ]
