version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.13

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install Chrome and Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv -f chromedriver /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver
      - run:
          name: Setup Django
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=webapp.settings
            echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"  # Ajout de cette ligne pour vérifier la variable d'environnement
            python -c "import os; print('DJANGO_SETTINGS_MODULE:', os.environ.get('DJANGO_SETTINGS_MODULE')); os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webapp.settings'); from django.core.wsgi import get_wsgi_application; application = get_wsgi_application()"
      - run:
          name: Verify SQLite
          command: |
            . venv/bin/activate
            python -c "import sqlite3; print('SQLite3 Version:', sqlite3.sqlite_version)"
      - run:
          name: Run Migrations
          command: |
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Install pytest
          command: |
            . venv/bin/activate
            pip install pytest
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=webapp.settings
            pytest --maxfail=3 --disable-warnings -v

workflows:
  version: 2
  all_jobs:
    jobs:
      - build-and-test
