version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.13
    working_directory: ~/repo
    environment:
      DJANGO_SETTINGS_MODULE: webapp.settings  # Définir ici
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install Chrome and Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv -f chromedriver /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver
      - run:
          name: Run Migrations
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=webapp.settings
            python manage.py migrate
      - run:
          name: Install pytest
          command: |
            . venv/bin/activate
            pip install pytest
      - run:
          name: Set environment variable
          command: |
            echo "export DJANGO_SETTINGS_MODULE=webapp.settings" >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=webapp.settings
            pytest

workflows:
  version: 2
  all_jobs:
    jobs:
      - build-and-test
