services:
  db:
    image: postgres:14.2
    env_file:
      - .env

    ports:
      - "5432:5432"

  web:
    image: cimg/python:3.11.0
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py test"
    depends_on:
      - db
    env_file:
      - .env
